title: Core Blimey! - Sitecore Blog   
description: Ian Graham's Sitecore Development Blog  

url: http://ianjohngraham.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

highlighter: rouge
gems: [jekyll-paginate]
paginate: 5


navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about


social:
   github: ianjohngraham
   twitter: ianjohngraham

google_analytics: "UA-58263416-1"

sass:
        sass_dir: _sass
