title: Coreblimey - Sitecore Blog
description: Sitecore Development Blog

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about


social:
   github: ianjohngraham
   twitter: ianjohngraham

google_analytics: "UA-58263416-1" 
